source 'https://rubygems.org'

gem 'eventmachine'
gem 'thin'
gem 'redis'
gem 'hiredis'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'rake'
gem 'beaneater'
gem 'json'
gem 'themis-checker-result'
gem 'ruby-ip'
gem 'themis-attack-result'
gem 'sequel'
gem 'sequel_pg'
gem 'ruby-enum'
