require './lib/configuration/team'
require './lib/configuration/service'
require './lib/configuration/postgres_connection'
require './lib/configuration/redis_connection'
require './lib/configuration/beanstalk_connection'
require './lib/configuration/contest_flow'
require './lib/configuration/network'
